import {
  Award,
  BadgeCheck,
  CheckCircle2,
  Clock,
  Cpu,
  Database,
  Gauge,
  Globe,
  HeadphonesIcon,
  Inbox,
  LifeBuoy,
  Lock,
  Mail,
  MousePointerClick,
  RefreshCw,
  Rocket,
  Search,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  Sparkles,
  Star,
  Terminal,
  TrendingUp,
  UserCog,
  Users,
  Wifi,
  Zap,
  ArrowRightLeft,
  type LucideIcon,
} from "lucide-react"

import type { IconOptionName } from "@/sanity/lib/icon-options"

/** Resolves a CMS-authored icon name (see `sanity/lib/icon-options.ts`) to its lucide-react component. */
export const iconMap: Record<IconOptionName, LucideIcon> = {
  Zap,
  TrendingUp,
  ShieldCheck,
  HeadphonesIcon,
  Server,
  Lock,
  Terminal,
  Search,
  Rocket,
  Gauge,
  Sparkles,
  Cpu,
  Mail,
  Shield,
  Inbox,
  Users,
  Globe,
  ArrowRightLeft,
  RefreshCw,
  MousePointerClick,
  UserCog,
  CheckCircle2,
  Star,
  Clock,
  Database,
  Wifi,
  Award,
  Settings,
  LifeBuoy,
  BadgeCheck,
}

export function resolveIcon(name?: string | null): LucideIcon | undefined {
  if (!name) return undefined
  return iconMap[name as IconOptionName]
}
