import {
  Activity,
  Award,
  BadgeCheck,
  BadgePercent,
  BookOpen,
  Boxes,
  CheckCircle2,
  Clock,
  Cpu,
  CreditCard,
  Database,
  Eye,
  Gauge,
  Globe,
  HardDriveDownload,
  HeadphonesIcon,
  HeartHandshake,
  Home,
  Inbox,
  KeyRound,
  LifeBuoy,
  Link2,
  Lock,
  Mail,
  MousePointerClick,
  Phone,
  RefreshCw,
  Rocket,
  ScanSearch,
  Search,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  Star,
  Target,
  Terminal,
  Ticket,
  TrendingDown,
  TrendingUp,
  UserCog,
  Users,
  Wallet,
  Wifi,
  Zap,
  ArrowRightLeft,
  type LucideIcon,
} from "lucide-react"

import type { IconOptionName } from "@/sanity/lib/icon-options"

/** Resolves a CMS-authored icon name (see `sanity/lib/icon-options.ts`) to its lucide-react component. */
export const iconMap: Record<IconOptionName, LucideIcon> = {
  Zap,
  TrendingUp,
  ShieldCheck,
  HeadphonesIcon,
  Server,
  Lock,
  Terminal,
  Search,
  Rocket,
  Gauge,
  Sparkles,
  Cpu,
  Mail,
  Shield,
  Inbox,
  Users,
  Globe,
  ArrowRightLeft,
  RefreshCw,
  MousePointerClick,
  UserCog,
  CheckCircle2,
  Star,
  Clock,
  Database,
  Wifi,
  Award,
  Settings,
  LifeBuoy,
  BadgeCheck,
  Phone,
  Ticket,
  BookOpen,
  BadgePercent,
  Link2,
  TrendingDown,
  Wallet,
  CreditCard,
  Home,
  Boxes,
  ShoppingCart,
  ScanSearch,
  KeyRound,
  Activity,
  HardDriveDownload,
  Eye,
  Target,
  HeartHandshake,
}

export function resolveIcon(name?: string | null): LucideIcon | undefined {
  if (!name) return undefined
  return iconMap[name as IconOptionName]
}
