import type { Metadata } from "next"

import { siteConfig } from "@/constants/site-config"
import { publicPath } from "@/lib/public-paths"
import { getSeoOverride } from "@/lib/cms/content"

type BuildMetadataOptions = {
  /** Short page title, e.g. "About Us" — the root layout's title template appends " | MagicWorks Host". */
  title: string
  description: string
  /** Site-relative path, e.g. "/hosting/vps-hosting". Defaults to "/". */
  path?: string
  /** Set true on pages that shouldn't be indexed (thank-you pages, etc.). */
  noIndex?: boolean
  /** "article" for blog posts; every other page type stays the default "website". */
  ogType?: "website" | "article"
  /** ISO 8601 timestamps — only meaningful when ogType is "article". */
  publishedTime?: string
  modifiedTime?: string
  /** The page's own share image (a blog post's featured image); defaults to the branded card. */
  image?: { url: string; width?: number; height?: number; alt?: string }
}

/** Default share image for every page — the branded card generated by app/opengraph-image.tsx. */
export const DEFAULT_SHARE_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: `${siteConfig.name} — ${siteConfig.tagline}`,
}

/**
 * Keyword-led <title>s for pages whose on-page headline is a slogan without the service
 * name ("Dedicated resources, without dedicated-server pricing" on the VPS page). Keyed by
 * internal route path. Used after the dashboard's SEO title and before the headline, so an
 * editor can still override any of them. Every phrase restates what the page itself says.
 */
const DEFAULT_SEO_TITLES: Record<string, string> = {
  "/vps-hosting": "VPS Hosting with Full Root Access & NVMe Storage",
  "/ssl": "Buy SSL Certificates – DV, OV, EV & Wildcard SSL",
  "/hosting": "Web Hosting Plans – NVMe Shared Hosting",
  "/hosting/seo-hosting": "SEO Hosting – Fast NVMe Hosting for Core Web Vitals",
  "/dedicated-hosting/dedicated-server": "Dedicated Server Hosting – Bare Metal, Full Root Access",
  "/domain": "Domain Names – Register, Transfer & Renew",
  "/domain/domain-name-registration": "Domain Name Registration – Register a Domain in Minutes",
  "/email-hosting": "Email Hosting – Professional Email on Your Domain",
  "/support": "24/7 Web Hosting Support",
  "/about-us": "About MagicWorks Host – Pune Web Hosting Since 2012",
  "/contact-us": "Contact Us – Hosting Sales & Support",
  "/blog": "Web Hosting Blog – Speed, Security & WordPress Guides",
}

/** The keyword-led default <title> for an internal route path, if it has one. */
export function defaultSeoTitle(path: string): string | undefined {
  return DEFAULT_SEO_TITLES[path]
}

const TITLE_MAX = 60
const DESCRIPTION_MIN = 70
const DESCRIPTION_MAX = 160

/** Keeps descriptions in the 70–160 character range search engines display in full. */
export function normalizeDescription(description: string): string {
  let text = description.replace(/\s+/g, " ").trim()
  if (text.length < DESCRIPTION_MIN) {
    const suffix = `${siteConfig.name}: NVMe hosting, domains, SSL and email with 24/7 support.`
    text = text ? `${text.replace(/[.\s]*$/, ".")} ${suffix}` : suffix
  }
  if (text.length > DESCRIPTION_MAX) {
    const cut = text.slice(0, DESCRIPTION_MAX - 1)
    text = `${cut.slice(0, cut.lastIndexOf(" ")).replace(/[,;:\s—–-]+$/, "")}…`
  }
  return text
}

/**
 * Single source of truth for per-page metadata — title, description, canonical,
 * Open Graph, and Twitter Card, all derived from the same inputs so pages can't
 * drift out of sync with each other. `title` is short; the root layout's title
 * template appends " | MagicWorks Host" — unless that would push the <title> past 60
 * characters, in which case the page title is used on its own so it isn't truncated.
 */
export function buildMetadata({
  title,
  description: rawDescription,
  path = "/",
  noIndex = false,
  ogType = "website",
  publishedTime,
  modifiedTime,
  image,
}: BuildMetadataOptions): Metadata {
  const canonical = publicPath(path)
  const url = canonical === "/" ? siteConfig.url : `${siteConfig.url}${canonical}`
  const withBrand = `${title} | ${siteConfig.name}`
  const fitsWithBrand = withBrand.length <= TITLE_MAX
  const fullTitle = fitsWithBrand ? withBrand : title
  const description = normalizeDescription(rawDescription)
  const shareImage = image ?? DEFAULT_SHARE_IMAGE
  const images = [shareImage]

  const openGraph: Metadata["openGraph"] =
    ogType === "article"
      ? { title: fullTitle, description, url, siteName: siteConfig.name, type: "article", locale: "en_IN", publishedTime, modifiedTime, images }
      : { title: fullTitle, description, url, siteName: siteConfig.name, type: "website", locale: "en_IN", images }

  return {
    title: fitsWithBrand ? title : { absolute: title },
    description,
    alternates: {
      canonical,
    },
    openGraph,
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
      images: [shareImage.url],
    },
    ...(noIndex ? { robots: { index: false, follow: false } } : {}),
  }
}

/**
 * Layers the per-path SEO saved in the admin (/admin/seo) over a page's computed metadata.
 * Admin SEO rows are keyed by the page's route path (`path`, e.g. "/legal/privacy-policy");
 * the canonical stays the public URL unless the admin sets one. Empty admin fields leave the
 * page's own values.
 */
export async function applySeoOverrides(metadata: Metadata, path = "/"): Promise<Metadata> {
  const seo = await getSeoOverride(path)
  const canonical = metadata.alternates?.canonical ?? publicPath(path)
  if (!seo) return metadata

  const title = seo.meta_title?.trim()
  const description = seo.meta_description?.trim()
  const ogTitle = seo.og_title?.trim() || title
  const ogDescription = seo.og_description?.trim() || description
  const ogImage = seo.og_image?.trim()
  const twitterImage = seo.twitter_image?.trim() || ogImage

  return {
    ...metadata,
    ...(title ? { title: { absolute: title } } : {}),
    ...(description ? { description } : {}),
    alternates: { ...metadata.alternates, canonical: seo.canonical_url?.trim() || canonical },
    openGraph: {
      ...metadata.openGraph,
      ...(ogTitle ? { title: ogTitle } : {}),
      ...(ogDescription ? { description: ogDescription } : {}),
      ...(ogImage ? { images: [{ url: ogImage }] } : {}),
    },
    twitter: {
      ...metadata.twitter,
      ...(seo.twitter_card ? { card: seo.twitter_card } : {}),
      ...(seo.twitter_title?.trim() || ogTitle ? { title: seo.twitter_title?.trim() || ogTitle } : {}),
      ...(seo.twitter_description?.trim() || ogDescription ? { description: seo.twitter_description?.trim() || ogDescription } : {}),
      ...(twitterImage ? { images: [twitterImage] } : {}),
    },
    ...(seo.no_index ? { robots: { index: false, follow: false } } : {}),
  }
}

/** `buildMetadata` + admin SEO overrides. Use from `generateMetadata`. */
export async function buildPageMetadata(options: BuildMetadataOptions): Promise<Metadata> {
  return applySeoOverrides(buildMetadata(options), options.path)
}
