/** Curated allow-list of lucide-react icon names editors can pick in Studio; kept in sync with `iconMap` in `@/lib/icon-map`. */
export const iconOptions = [
  "Zap",
  "TrendingUp",
  "ShieldCheck",
  "HeadphonesIcon",
  "Server",
  "Lock",
  "Terminal",
  "Search",
  "Rocket",
  "Gauge",
  "Sparkles",
  "Gauge",
  "Cpu",
  "Mail",
  "Shield",
  "Inbox",
  "Users",
  "Globe",
  "ArrowRightLeft",
  "RefreshCw",
  "MousePointerClick",
  "UserCog",
  "CheckCircle2",
  "Star",
  "Clock",
  "Database",
  "Wifi",
  "Award",
  "Settings",
  "LifeBuoy",
  "BadgeCheck",
  "Phone",
  "Ticket",
  "BookOpen",
  "BadgePercent",
  "Link2",
  "TrendingDown",
  "Wallet",
  "CreditCard",
  "Home",
  "Boxes",
  "ShoppingCart",
  "ScanSearch",
  "KeyRound",
  "Activity",
  "HardDriveDownload",
  "Eye",
  "Target",
  "HeartHandshake",
] as const

export type IconOptionName = (typeof iconOptions)[number]
